baseurl = "http://www.matthewopala.com"
title = "Matthew Opala - Software Development"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "mopala"

[params]
    author = "Matthew Opala"
    description = "Matthew Opala's personal website"
    keywords = "software engineering, machine learning, deep learning"
    info = "Machine Learning Tech Lead"
    avatarurl = "images/mati.jpeg"
    logourl = "images/logo.png"
    footercontent = "Enter a text here."

    dateformat = "June 14, 2020"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
    # siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
    # serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/plazowicz/"
# [[params.social]]
#     name = "Gitlab"
#     icon = "fab fa-gitlab"
#     weight = 2
#     url = "https://gitlab.com/johndoe/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/matthewopala/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/matthewopala/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://medium.com/@matthewopala"
# [[params.social]]
#     name = "RSS"
#     icon = "fas fa-rss"
#     weight = 6
#     url = "https://myhugosite.com/index.xml"
#     rel = "alternate"
#     type = "application/rss+xml"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "contact/"

    [languages.pl]
        languagename = "Polski"
        title = "Mateusz Opala Software Development"

        [languages.pl.params]
            author = "Mateusz Opala"
            description = "Strona domowa Mateusza Opali"
            keywords = "programowanie, sztuczna inteligencja, uczenie maszynowe"
            info = "Programista i in≈ºynier uczenia maszynowego"
            footercontent = "footer content"

        [languages.pl.menu]

            [[languages.pl.menu.main]]
            name = "O mnie"
            weight = 1.0
            url = "/pl/about/"

            [[languages.pl.menu.main]]
            name = "Blog"
            weight = 2.0
            url = "/pl/posts/"

            [[languages.pl.menu.main]]
            name = "Projekty"
            weight = 3
            url = "projects/"

            [[languages.pl.menu.main]]
            name = "Kontakt"
            weight = 5
            url = "contact/"